### ISSUE TITLE
Should the SCAR be a voting representative?

### ISSUE THREAD

**Issue by mitchcieminski** [olin/studentgovernment#14]
We discussed this in the 2016-03-21 meeting, and it was decided to "put it off to a later date." Do actually discuss this and put forth an amendment to the by-laws.

**Comment by newsch** [comment]
Per [Article 3, Section 3 of the constitution](https://github.com/olin/studentgovernment/blob/master/student_government_constitution.md#section-3-structure-1), this is solely a by-laws matter.

**Comment by newsch** [comment]
An interesting, if unrelated tidbit: the constitution doesn't require class representatives, only that at least one member from each class is on CORe.

**Comment by mitchcieminski** [comment]
That was very much intentional.

**Comment by newsch** [comment]
Some relevant links:
- [Article 2, Section 19](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-19-ad-hoc-representatives) (the current definition of the SCAR position)
- [Article 2, Section 5](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-4-class-representatives) (the most-likely location of the SCAR position if redefined as a voting member)
- [2016-03-21 meeting minutes](https://docs.google.com/document/d/1iBqgicgNmOAZL52U9DJWDRbzGyOKYw7K-YXHOrffXd0/edit?usp=sharing) - I'm afraid they don't have much info in them
- [the relevant amendment from 2016 (#11)](https://github.com/olin/studentgovernment/pull/11)

**Comment by anushadatar** [comment]
Voted to close this [here](https://docs.google.com/document/d/1mKrKKW_Bj3Cr-Z43Z86IpRbWxndPeKN0cXQTJnVsIoQ/edit?usp=sharing)
