### ISSUE TITLE
Elections clarification

### ISSUE THREAD

**Issue by mitchcieminski** [olin/studentgovernment#19]
Basically, the election section is not super clear about a variety of things.
## Eligibility

> A student may run for any combination of positions but may only hold one voting position on the Student Government.

It should be made clearer that the SCAR and the Honor Board general members are the non-voting elected positions. Unless this sentence also refers to Assistant Directors, who are generally non-voting, in which case it needs to be made a LOT clearer what it actually refers to.

> Rising Sophomores, Juniors, and Seniors are eligible . . . Rising Sophomores and Juniors are eligible . . . if a Rising Senior was not elected . . .

This is a confusing way to say the following: 

"Any student matriculating at Olin in the following year may run for any position in the student government, as long as the following restrictions are met at all times: A Senior can not be the Vice President of Finance: a Senior cannot be the Assistant Director of a committee if the Director of that committee is a Senior; the Chair and Vice Chair of the Honor Board can not be in the same graduating class; and Class Representatives must be a member of the class that they represent."

Or something like that.
## Election Monitor

> The Election Monitor enforces campaigning rules and guidelines defined in the By-Laws.

The election monitor should not only enforce campaign rules, but also be the final authority on campaigning restrictions.

> In the case of no candidates, the Dean of Student Life performs the duties of the Election Monitor.

The duty should probably fall to the Senior Class representative or another Senior member of the student government instead.
### Overarching changes

> candidates may campaign in a respectful and appropriate manner.

This should be more forceful, and be the overarching campaign rule. "Candidates _must_ campaign in a respectful and appropriate manner, as defined by the election monitor."

> To preserve an intellectual atmosphere and guarantee equal opportunities of election

This statement should be moved so that it is the guideline for the election monitor to determine what is "respectful and appropriate" 

> campaigning outside of the following rules is prohibited

It should be clarified that this is not an exhaustive set of rules.
### Rules to be added

The following should be codified as additional rules, or be changed. These come from possible issues that people have pointed out to me, or things that actually happened.
- third parties may not campaign for other students without that candidate's explicit permission
- campaign materials cannot contain inappropriate or offensive content
- students should be able to campaign in the library, at the ACRONYM, or possibly in the auditorium. The rule about not campaigning in Milas should be changed to allow for these cases. The overall rule could probably become "Candidates may not campaign in academic spaces or offices. Acceptable places to campaign include outdoors, the dormitories, the public spaces in the campus center, the library, the Milas Hall atrium, and the Norden Auditorium."
## Voting

> Members of the Student Government are elected by excellence voting - a student may vote for as many of the candidates as they feel would excel in, and are qualified for, the position.

Excellence voting is a muddy concept. This last election, I wrote specifically that a vote for none of the candidates was a vote against those candidates, rather than an abstention from that particular sub-election. A way to make this clear would be asking candidate by candidate: "Would Frank Olin be an excellent candidate for CORe President?" and have the answers be "yes" "no" or "abstain." Another way to do this would be "place each of the candidates into one of the following categories: 'Would be excellent' 'would not be excellent' or 'I don't know/have no opinion.' This also allows uninformed voters to honestly cast ballots, which might not be a bad thing.

Adding in explicit abstention rules might make it more difficult for students to be elected, because "the winner must be considered qualified by at least 50% of voters," according to a later section. This isn't necessarily bad, as it means more of the student government would be enthusiastically approved by the student body.

> For the position of Vice Chair of the Honor Board, the winner is the student who is not in the same class as the newly elected chair who has the most excellence votes and who has garnered at least 50% of the votes.

This could be easily changed from an exception to the rule to a part of the regular committee directors rules. In the system as it stands now, the Chair and Vice Chair of the Honor Board are elected simultaneously and then this restriction is added. If the Vice Chair of the Honor Board was elected in Cycle 2, like all other Assistant Directors, then this rule wouldn't really have to be different from the general rules stating that Seniors can only run for assistant director positions if a Senior was not elected director. We'd still have to add in the caviat that no member of the Director's class can run for Assistant Director.

Now that I'm thinking about it, I'm not sure if this is the best change to be made, because it might keep people from running for Vice Chair if that's all they want to run for. I don't know, think about it.

> For Honor Board General Members, the winners are the students with the most excellence votes and who have garnered at least 50% of the votes, given that at the end of Fall Elections, there is at least one student from each class on the Honor Board.

This is a potentially difficult policy to put into place. It would instead probably be easier if, in the spring, each class was guaranteed one general member and a fourth one could be from any class, and then in the spring, the first years were guaranteed one general member and a second one could be from any class.

**Comment by newsch** [comment]
Relevant links:
- [Article 10 (Constitution)](https://github.com/olin/studentgovernment/blob/master/student_government_constitution.md#article-10-election-procedures)
- [Article 11 (By-Laws)](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#article-11-election-procedures)

**Comment by anushadatar** [comment]
Submitted a PR regarding the [Election Monitor](https://github.com/olin/studentgovernment/pull/62)  issue. Seeking discussion of this issue at the 2/5 meeting to determine if there is anything else that has not yet been addressed and to propose we close this issue if everything has been addressed.

**Comment by anushadatar** [comment]
Voted to close this issue on [2/5 meeting](https://docs.google.com/document/d/1n5X4QGQSKQhCmArCxcI23BoIlx-kC5Rg4TPSb1bI8qo/edit?usp=sharing)
