### ISSUE TITLE
CCO Changes

### ISSUE THREAD

**Issue by mitchcieminski** [olin/studentgovernment#20]
I'd like to change the following in the CCO section.
## Make a list

Add to [the description of the Director of Clubs and Organizations](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-2-officers) that they are responsible for maintaining a publicly-accessible (even outward-facing) list of all Student Groups on campus, both ones that are currently active and ones that are defunct. This list would ideally include contact information for each club as well, although maybe the contact information should only be available to the public upon request. It would aim to be exhaustive, though not be required to be exhaustive. It should also be updated like once a month.
## Require that list in the transparency documents

Add The List of All Student Groups to the [Transparency Documents Section](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-2-transparency-documents)
## Recognize non-clubs and non-orgs as "student groups" for the purposes of listmaking

A new category should be added to the [Student Group Classifications](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-5-student-group-classifications): **Student Groups not generally funded by CCO.** This could have some sub-groups, such as Academic Project Teams, Co-Curriculars, Teaching Teams, Student Government Committees, the Student Government and CORe, and Informal Groups. I would also be OK with adding that any group in this category _could_ request funding from CCO, with the understanding that they will probably be denied excepting circumstances that they are really acting "as a club."
## Change the [definition of a club](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-5-student-group-classifications).

If we added a third categorization of "Student Groups not generally funded by CCO," then clubs are no longer really the "default." Joe and I created the following definition of a club earlier in the year: "A student-led part of the larger Olin Community with a common goal, interest, mission, or ideology." This would serve as a good start to redefining clubs, but the new definition isn't quite good enough because of some funding kinks.

This particular definition (for both clubs and orgs) is really tricky because we have to exclude "established" teams like Baja or REVO while funding and allowing the creation of new academic teams like Aero or Aquaponics. "Clubs do not financially sustain themselves through soliciting donations" seems like a start toward allowing this, but it might exclude things like SLAC depending on how much money they're raising in a given year. In this definition, a Project Team could decide to not raise any funds anymore and then ask to be funded as a club. Finally, it does weird things for groups like SWE, which I generally say can spend club money on club events and spend their own, donated money on things like conferences. A simple "clubs are not academic in nature" cuts out things like Midnight Math, while "clubs are things like those that are considered clubs today" is too self-referential and circular.
## Change the [definition of an org](https://github.com/olin/studentgovernment/blob/master/student_government_bylaws.md#section-5-student-group-classifications)

If we have a good definition of a club, you can basically just say that an org is a large or significant club. You change "A student group may petition" to "a club or organization may petition," and say that org status is granted for one-year periods at a time.
## Add a bit about club fair

The Director and Assistant Director are the _de facto_ responsible parties for organizing club fairs. This should be made explicit. They should just be responsible for organizing club fair, which must be open to all student groups on the list. CCO should also be able to give all student groups some amount of money (we've usually gone $20) to spend on club fair items or food. This includes both the beginning-of-the-year one and the candidates weekend ones, as well as any that might pop up over the course of the year.
## Meetings

At least one meeting should be called at the beginning of every semester to inform club + organization leaders of club spending rules, org budget rules, and train people to spend money. All members of the student government should try to attend, mostly for their convenience.

A meeting should be called toward the end of every year for the purpose of having a general discussion of the state of extracurricular activities at Olin, recognize outstanding clubs or events, and remind student leaders to transition their clubs.

Informal meetings should be held every other week as "CCO office hours" so that CCO officers can learn about club goings-on and help clubs do their things.
## Charters

All clubs and organizations should be required to have charters to recognized as clubs or organizations, and not simply "other student groups." What counts as a charter should be defined. It should be the responsibility of CCO officers to maintain a repository of these charters that is accessible to all students and editable by members of the club or organization, so long as those edits are allowed by their charter.
## Reform food-related rules

I have no idea what the right way with the food-related rules is, but I know that what we have isn't them

**Comment by anushadatar** [comment]
Going through each of the individual comments:
## Make a List
This has been codified in [Article 13 Section 2](https://github.com/olin/studentgovernment/blob/master/bylaws.md#section-2-transparency-documents) under the List of Student Groups. This list includes all the names of all of the clubs

## Require that List in the Transparency Documents
 This has been codified in [Article 13 Section 2](https://github.com/olin/studentgovernment/blob/master/bylaws.md#section-2-transparency-documents) under the List of Student Groups.

$$ Recognize non-clubs and non-orgs as "student groups" for the purposes of listmaking

**Comment by anushadatar** [comment]
After thinking more about it, it looks like it makes the most sense to propose two PRs - one PR that adds a section of additional responsibilities to the CCO Article which asks it to track additional student groups for the purposes of listmaking (and curate the list of the student groups in general) and a second PR to cover the charter requirement.

**Comment by anushadatar** [comment]
Voted to close this issue at the [2/5 meeting](https://docs.google.com/document/d/1n5X4QGQSKQhCmArCxcI23BoIlx-kC5Rg4TPSb1bI8qo/edit?usp=sharing)
