### ISSUE TITLE
Recognize religious objections.

### ISSUE THREAD

**Issue by mitchcieminski** [olin/studentgovernment#21]
See pull #18 to see something that didn't pass.

It's been said by multiple people that it's important that the student government _at least_ consider religious holidays and traditions before scheduling events for the student body. Read the pull request to see some discussion on it.

Please fix this eventually. It seems to very squarely fall into the "Respect for Others" clause of the Honor Code.

> I will be patient with and understanding of fellow community members, and considerate of their inherent dignity and personal property. I will care for community resources and facilities so others may effectively use them.

**Comment by newsch** [comment]
- [previous pull request](https://github.com/olin/studentgovernment/pull/18)
- [minutes from original meeting](https://docs.google.com/document/d/1u9_e-XJ4PV1ee5FpJC_FF8qvXEuGDMA307DPDjSy7PU/)

**Comment by anushadatar** [comment]
Proposing to close this issue at the December 4th SG meeting.

Explicitly cataloging religious objections is not flexible to holidays on the lunar calendar (unless constantly updated and re-approved, which is super high overhead). Part of being involved in student government is following the respect for others clause and thinking about scheduling with a robust set of constraints.

At the same time, there's definitely a concern that religious obligations/traditions fewer students are involved in will feel an outsized impact from a lack of policy on this. Plan is to discuss whether or not there is a need for broader guidelines around event scheduling in general or if this is outside the scope of what SG can and can't regulate from a high level. 

This will be discussed at the meeting prior to a vote about next steps.

**Comment by anushadatar** [comment]
We had a pretty robust discussion about this at the [12/5](https://docs.google.com/document/d/1uFAjqx9bZrjbd-uN2i57kGZg_zhPvtcGLRUWuzWtOYM/edit?usp=sharing) meeting of SG and then chose to close this issue (see notes)
