### ISSUE TITLE
 80 character line widths

### ISSUE THREAD

**Issue by MattWis** [olin/studentgovernment#3]
I feel like an old man writing this, but it's pretty hard to see what's actually changed when an entire paragraph is on the same line. Markdown supports having mulitple-line paragraphs well, and github will even highlight the characters/words that have changed on shorter lines. (Like this commit: https://github.com/olin/slac/commit/143a89e7af94f5c55d125ecdc150c9bf54f6d566) 

Is this a thing worth doing? Technically it's feasible, but I don't know if whitespace-only changes are allowed, or if there needs to be an amendment for this. (I'm way too lazy to go through the amendment process for some whitespace, but I could easily whip up a PR for this change if that's legal.)

Related: I've been staring at the changes in the second paragraph of https://github.com/olin/studentgovernment/pull/2 for about 10 minutes now, and I'm only pretty sure nothing's changed.

**Comment by iangmhill** [comment]
Hi Matt - I believe this is worth doing. As you said, it will make reading amendments much easier. As long as the wording of both documents remains exactly the same, I think it's fine to submit a PR for improve the formatting. If you create a PR, I'll approve it.

**Comment by iangmhill** [comment]
Fixed by pull request #4
