### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by newsch** [olin/studentgovernment#35]
It would be nice to have a document that contains some meta guidelines for interacting with the constitution and bylaws, formatting pull requests and suggestions, etc. The standard for this in the GitHub world is a [CONTRIBUTING.md file](https://blog.github.com/2012-09-17-contributing-guidelines/). I've started [one in the `newsch-add-contributing` branch](https://github.com/olin/studentgovernment/blob/newsch-add-contributing/CONTRIBUTING.md).

**Comment by anushadatar** [comment]
Completed via https://github.com/olin/studentgovernment/pull/42
