### ISSUE TITLE
Change wording of "List of Student Groups and Administration Committees"

### ISSUE THREAD

**Issue by newsch** [olin/studentgovernment#44]
[Line 1129](https://github.com/olin/studentgovernment/blame/71c78da935438d35599351ec231129b06342ecda/student_government_bylaws.md#L1129)

"Administration Committees" doesn't really encompass non-student groups anymore.

**Comment by anushadatar** [comment]
Would it be more appropriate to just call this the 'List of Student Groups'? @newsch are there groups of not students that we ought to be keeping track of?

**Comment by anushadatar** [comment]
I'll submit a PR to be reviewed at the 12/04 meeting of the Council, we can discuss it further at that time.

**Comment by anushadatar** [comment]
Drafted https://github.com/olin/studentgovernment/pull/59 - would appreciate feedback before 12/04 meeting @newsch

**Comment by anushadatar** [comment]
Voted to approve at [12/5](https://docs.google.com/document/d/1uFAjqx9bZrjbd-uN2i57kGZg_zhPvtcGLRUWuzWtOYM/edit?usp=sharing) mmeeting. Closing issue.
