### ISSUE TITLE
Duplicate Appeals Process

### ISSUE THREAD

**Issue by ljordan51** [olin/studentgovernment#82]
Just realized that the appeals process in the related policies and procedures doesn't clearly say if it is specifically for students of other colleges. If it is, it should be clarified. If not, it is redundant (and actually ever so slightly different than the appeals process in 4.2. We should probably resolve that at the honor board town hall at the start of the 2020-2021 school year.

**Comment by intermezzio** [comment]
This will be addressed in #92

**Comment by intermezzio** [comment]
Resolved in https://github.com/olin/studentgovernment/pull/92
