### ISSUE TITLE
Amendments section doesn't mention proxy voting

### ISSUE THREAD

**Issue by ljordan51** [olin/studentgovernment#87]
Seems like it should be mentioned since we use it so much

**Comment by anushadatar** [comment]
Agreed it makes sense to add this to the honor code. Labeling it honorcode and leaving what is mentioned in the SG constitution re: proxy voting in case i makes sense to evaluate that as well. 

Article 13. Ratification and Review
Section 1. Ratification.
For this Student Government Constitution to go into effect, it must be ratified by a simple majority vote of the Students present at a Town Hall Meeting where quorum is one half of the Student Body, including proxy voters.
